#!/bin/sh -ex

. inc/common

tuning_level=`config-get tuning`
engine=`config-get engine`
unit_address=`unit-get private-address`


version=`config-get version`
uber=`config-get uber`

install_drupal(){

      juju-log "Install Drupal version $version"
      rm -fr $install_path
      mkdir -p $install_path

      juju-log "Download"
      TARBALL="http://ftp.drupal.org/files/projects/drupal-"$version".tar.gz"
      curl -vv -L $TARBALL > /tmp/drupal.tar.gz

      juju-log "Extract"
      tar -C $install_path --strip-components=1 -zxf /tmp/drupal.tar.gz
      rm -f /tmp/drupal.tar.gz
      if [ $version = "6.34" ]
         mv $install_path/sites/default/default.settings.php $install_path/sites/default/settings.php
      fi
      set_permissions
      echo $version > .version
}


if [ -f .version ]; then
   if [ "x$(cat .version)" = "x$version" ]; then 
      juju-log "Drupal version $version already installed"
   else
      install_drupal
   fi
else
install_drupal
fi



if [ "x$engine" = "xapache" -o "x${engine}" = "xapache2" ]; then
	if [ -f .web-engine ]; then
		web_engine=`cat .web-engine`
		service $web_engine stop
	fi
	apt-get -y purge nginx
	apt-get --no-install-suggests --no-install-recommends install -y apache2 libapache2-mod-php5
	service apache2 stop

  mkdir -p /srv/www/htdocs

  rm -f /etc/apache2/sites-available/*
	rm -f /etc/apache2/sites-enabled/*
	a2enmod actions rewrite alias headers php5

	juju-log "Installing Apache loadbalance config..."
	install -o root -g root -m 0644 files/charm/apache/etc_apache2_sites-enabled_loadbalancer /etc/apache2/sites-available/loadbalancer.conf
	sed -i -e "s/^  ServerName .*/  ServerName ${unit_address}/" /etc/apache2/sites-available/loadbalancer.conf
	a2ensite loadbalancer

	juju-log "Installing Apache drupal config..."
	install -o root -g root -m 0644 files/charm/apache/etc_apache2_sites-enabled_drupal /etc/apache2/sites-available/drupal.conf
	a2ensite drupal

	echo "apache2" > .web-engine
fi


hooks/loadbalancer-rebuild

juju-log "Restarting Services ..."
hooks/restart
