#!/bin/sh -ex

juju-log "We've got a db"

. inc/common

database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`
version=`config-get version`

if [ -z "$database" ] ; then
	exit 0
fi

config_file=""
if [ -e $install_path/sites/default/settings.php ];then
    config_file="$install_path/sites/default/settings.php"
else
    config_file="$install_path/sites/default/default.settings.php"
fi

if [ $version = "6.34"];then
 sed -i "s|\$db_url = 'mysql://username:password@localhost/databasename';|\$db_url = 'mysql://$user:$password@$host/$database';|g" $config_file
else
  cat <<EOF >> $config_file
    \$databases['default']['default'] = array(
    'driver' => 'mysql',
    'database' => '$database',
    'username' => '$user',
    'password' => '$password',
    'host' => '$host',
    'prefix' => '',
    'collation' => 'utf8_general_ci',
    );
   EOF
fi





juju-log "Resetting permissions"

chown -R www-data.www-data $install_path

hooks/config-changed
hooks/restart

# Make it publicly visible, once the drupal service is exposed
open-port 80/tcp
open-port 443/tcp
