#!/bin/sh -ex

juju-log "Join relations"

database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`
version=`config-get version`

if [ -z "$database" ] ; then
    exit 0
fi
