#!/bin/sh -ex

. inc/common

apt-get update
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 pwgen php-pear php5-gd php5 php5-mysqlnd exim4-daemon-light

a2enmod php5 headers
a2dissite 000-default

service apache2 restart

: <<EOF

#install drush so that we are prepared to deploy 
pear channel-discover pear.drush.org
pear install drush/drush

drupal-download
EOF

juju-log "Download"
TARBALL="http://ftp.drupal.org/files/projects/drupal-7.33.tar.gz"
curl -vv -L $TARBALL > /tmp/drupal.tar.gz

juju-log "Extract"
mkdir -p $install_path
tar -C $install_path --strip-components=1 -zxf /tmp/drupal.tar.gz
rm -f /tmp/drupal.tar.gz

set_permissions
