#!/bin/sh -ex

. inc/common

apt-get update
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 pwgen php-pear php5-gd php5 php5-mysqlnd exim4-daemon-light

a2enmod php5 headers
a2dissite 000-default

service apache2 restart