#!/bin/sh -ex

. inc/common

apt-get update
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 pwgen php-pear php5-gd php5 php5-mysqlnd exim4-daemon-light

a2enmod php5 headers
a2dissite 000-default

service apache2 restart


sed -i "s|dc_eximconfig_configtype='local'|dc_eximconfig_configtype='internet'|g" /etc/exim4/update-exim4.conf.conf

update-exim4.conf
